### ISSUE TITLE
Using It-

### ISSUE THREAD

**Issue by bonds77** [Elkfox/Shopify-Subscribe-Form#2]
I have no idea how to get this going. Not a programmer by trade- I have installed all the .css and .liquid. Can you point me?

**Comment by cam** [comment]
Hi @bonds77. It's not the easiest sort of thing to work with if you aren't familiar with coding. If you [get in touch with our expert team](https://experts.shopify.com/elkfox?ref=elkfox), I am sure it would be a very quick and cheap job for them to install it for you.
